// Code generated by MockGen. DO NOT EDIT.
// Source: go_fiber_wibowo/app/module/web_page/repository (interfaces: WebPageRepository)

// Package repository is a generated GoMock package.
package repository

import (
	schema "go_fiber_wibowo/app/database/schema"
	request "go_fiber_wibowo/app/module/web_page/request"
	request0 "go_fiber_wibowo/app/request"
	paginator "go_fiber_wibowo/utils/paginator"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWebPageRepository is a mock of WebPageRepository interface.
type MockWebPageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebPageRepositoryMockRecorder
}

// MockWebPageRepositoryMockRecorder is the mock recorder for MockWebPageRepository.
type MockWebPageRepositoryMockRecorder struct {
	mock *MockWebPageRepository
}

// NewMockWebPageRepository creates a new mock instance.
func NewMockWebPageRepository(ctrl *gomock.Controller) *MockWebPageRepository {
	mock := &MockWebPageRepository{ctrl: ctrl}
	mock.recorder = &MockWebPageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebPageRepository) EXPECT() *MockWebPageRepositoryMockRecorder {
	return m.recorder
}

// CheckExist mocks base method.
func (m *MockWebPageRepository) CheckExist(arg0 string) (*schema.WebPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExist", arg0)
	ret0, _ := ret[0].(*schema.WebPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExist indicates an expected call of CheckExist.
func (mr *MockWebPageRepositoryMockRecorder) CheckExist(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExist", reflect.TypeOf((*MockWebPageRepository)(nil).CheckExist), arg0)
}

// Create mocks base method.
func (m *MockWebPageRepository) Create(arg0 *schema.WebPage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWebPageRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebPageRepository)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockWebPageRepository) Delete(arg0 request.WebPageDeleteRequest, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWebPageRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWebPageRepository)(nil).Delete), arg0, arg1)
}

// FindByUserId mocks base method.
func (m *MockWebPageRepository) FindByUserId(arg0 string) ([]*schema.WebPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserId", arg0)
	ret0, _ := ret[0].([]*schema.WebPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserId indicates an expected call of FindByUserId.
func (mr *MockWebPageRepositoryMockRecorder) FindByUserId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserId", reflect.TypeOf((*MockWebPageRepository)(nil).FindByUserId), arg0)
}

// FindOne mocks base method.
func (m *MockWebPageRepository) FindOne(arg0 string) (*schema.WebPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0)
	ret0, _ := ret[0].(*schema.WebPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockWebPageRepositoryMockRecorder) FindOne(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockWebPageRepository)(nil).FindOne), arg0)
}

// GetAll mocks base method.
func (m *MockWebPageRepository) GetAll(arg0 request0.Pagination) ([]*schema.WebPage, paginator.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]*schema.WebPage)
	ret1, _ := ret[1].(paginator.Pagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockWebPageRepositoryMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockWebPageRepository)(nil).GetAll), arg0)
}

// Update mocks base method.
func (m *MockWebPageRepository) Update(arg0 string, arg1 *schema.WebPage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWebPageRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWebPageRepository)(nil).Update), arg0, arg1)
}
